import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const projects=JSON.parse(fs.readFileSync(new URL('../src/data/projects.json',import.meta.url))),p=projects.find(p=>p.slug==='experience');
test('GIAS identity and professional ownership are exact',()=>{assert.equal(p.employment.role,'Business Analyst');assert.equal(p.employment.startDate,'2021-01');assert.equal(p.employment.endDate,'2023-12');assert.equal(p.employment.type,'Full-time');assert.equal(p.employment.location,'Vadodara, Gujarat, India');assert.equal(p.employment.workMode,'Hybrid');assert.match(p.chapters[0].detail,/management and finance retained final pricing, accounting, commission-policy and commercial authority/);});
test('the existing seven scene identities and media remain intact',()=>{assert.deepEqual(p.chapters.map(c=>c.id),['chapter-0','chapter-1','opening-evidence','chapter-2','chapter-3','chapter-4','skills-tools']);assert.deepEqual(p.chapters.map(c=>[c.scene.asset,c.scene.frame||0]),[['/worlds/gias-city.png',0],['/worlds/gias-scenes.png',0],['/worlds/gias-city.png',0],['/worlds/gias-scenes.png',1],['/worlds/gias-scenes.png',2],['/worlds/gias-scenes.png',3],['/worlds/gias-finale.png',0]]);});
test('eight workflows explain variants and finance remains the authority',()=>{assert.equal(p.chapters[2].objects.length,8);assert.match(p.chapters[2].body,/20\+ sale, rental and lease workflow variants/);assert.match(p.chapters[2].objects[2].detail,/Finance remained the accounting authority/);assert.match(p.chapters[2].objects[6].detail,/visits that did not close/);});
test('only the six supplied scale/outcome metrics are used',()=>{assert.deepEqual(p.scopeMetrics.map(m=>m.value),['3 years','1,000+','5+','20+','10+','Approximately 30%']);assert.deepEqual(p.chapters[5].metrics,p.scopeMetrics);assert.match(p.scopeMetrics[5].label,/management feedback/);});
test('role skills, applications and methods stay distinct without project technologies',()=>{assert.equal(p.skills.length,20);assert.equal(new Set(p.linkedSkills).size,20);assert.deepEqual(p.tools.map(t=>t.name),['Microsoft Excel','Tableau']);assert.equal(p.methods.length,4);assert.equal(p.toolchainGroups,undefined);assert.doesNotMatch(JSON.stringify([p.skills,p.tools,p.methods]),/Python|machine learning|RAG|React|TypeScript|AI governance/);});
test('all eleven management questions and evidence links are retained',()=>{const content=p.chapters[3].objects.flatMap(o=>o.visualData.content);assert.equal(content.filter(s=>s.endsWith('?')).length,11);assert.ok(p.links.some(l=>l.url==='https://gias.in/'));assert.ok(p.links.some(l=>l.url==='https://www.linkedin.com/company/global-infrastructure-advisory-service/'));assert.ok(p.links.some(l=>l.url==='https://www.linkedin.com/in/praveen-rathee-8b028030b/details/recommendations/'));});
test('production Experience HTML supplies metadata without JavaScript',()=>{const html=fs.readFileSync(new URL('../dist/experience/index.html',import.meta.url),'utf8');assert.ok(html.includes('<title>'+p.metadata.title+'</title>'));assert.ok(html.includes('property="og:description" content="'+p.metadata.description+'"'));assert.match(html,/rel="canonical" href="https:\/\/ai-portfolio-kohl-beta.vercel.app\/experience"/);});
