export type FloorPoint={x:number;rise:number;depth:number};
export type FloorOpenings=Record<number,{x:number;open:boolean}>;
export function rememberDescent(openings:FloorOpenings,from:number,to:number,x:number){if(!Number.isFinite(x)||from<1||to<=from)return;for(let floor=from;floor<to;floor++)openings[floor]={x,open:true};}
export function repairAscent(openings:FloorOpenings,to:number,from:number){for(let floor=to;floor<from;floor++)if(openings[floor])openings[floor].open=false;}
export type SceneMoment={x:number;facing:'visitor'|'world'|'left'|'right';thought:number;activity:string};
export type HomeFloor={name:string;route:number[];moments:SceneMoment[];surface:FloorPoint[];entry:{x:number;rise:number;depth:number}};
// Coordinates are local to the reserved right-hand scene area; rise is measured from its foreground floor.
export const homeFloors:Record<number,HomeFloor>={
 1:{name:'Mountain portal steps',route:[48,62,74,59,39,26],moments:[{x:48,facing:'visitor',thought:0,activity:'Introduce the business question'},{x:62,facing:'world',thought:1,activity:'Look back through the mountain portal'},{x:74,facing:'world',thought:2,activity:'Pause on the upper property-view step'},{x:59,facing:'left',thought:2,activity:'Inspect the reporting objects'},{x:39,facing:'right',thought:3,activity:'Present code review and validation'},{x:26,facing:'visitor',thought:0,activity:'Return to the foreground'}],entry:{x:68,rise:95,depth:.38},surface:[{x:20,rise:0,depth:1},{x:43,rise:0,depth:1},{x:55,rise:8,depth:.98},{x:65,rise:19,depth:.94},{x:78,rise:34,depth:.87}]},
 2:{name:'Gallery terrace',route:[31,49,68,76,56,25],moments:[{x:31,facing:'visitor',thought:0,activity:'Introduce the collection'},{x:49,facing:'right',thought:1,activity:'Explore Gold workbooks and models'},{x:68,facing:'world',thought:2,activity:'Look into the connected-work universe'},{x:76,facing:'world',thought:3,activity:'Survey the campaign terrace'},{x:56,facing:'left',thought:4,activity:'Present ingredient and logistics objects'},{x:25,facing:'visitor',thought:0,activity:'Return to the entrance edge'}],entry:{x:62,rise:70,depth:.5},surface:[{x:20,rise:7,depth:.98},{x:38,rise:7,depth:.98},{x:51,rise:15,depth:.95},{x:66,rise:27,depth:.91},{x:78,rise:39,depth:.86}]},
 3:{name:'Garden stairway',route:[44,61,73,57,34,23],moments:[{x:44,facing:'visitor',thought:0,activity:'Introduce original sources'},{x:61,facing:'left',thought:1,activity:'Inspect the tool collection'},{x:73,facing:'world',thought:2,activity:'Look outward from the upper garden stair'},{x:57,facing:'right',thought:3,activity:'Present original documents'},{x:34,facing:'visitor',thought:4,activity:'Explain the motion control'},{x:23,facing:'world',thought:0,activity:'Turn toward the archive vista'}],entry:{x:66,rise:80,depth:.45},surface:[{x:20,rise:0,depth:1},{x:39,rise:0,depth:1},{x:51,rise:8,depth:.98},{x:64,rise:20,depth:.94},{x:78,rise:35,depth:.88}]}
};
export function floorPoint(section:number,x:number):FloorPoint{const points=(homeFloors[section]||homeFloors[1]).surface;const bounded=Math.max(points[0].x,Math.min(points.at(-1)!.x,x));const hi=points.findIndex(p=>p.x>=bounded);if(hi<=0)return{...points[0],x:bounded};const a=points[hi-1],b=points[hi],t=(bounded-a.x)/(b.x-a.x);return{x:bounded,rise:a.rise+(b.rise-a.rise)*t,depth:a.depth+(b.depth-a.depth)*t};}
