import {useEffect,useRef,useState} from 'react';
import type {CSSProperties} from 'react';
import './homeGuide.css';
import GuideProps from './GuideProps';
const thoughts:Record<number,string[]>={
 1:["I start with the business question—then work out what information can answer it.","My background combines Business Analysis, an MBA in Operations & Supply Chain, and Physics.","At GIAS, my work connected property records, stakeholder questions and recurring reporting.","For technical projects, I direct the requirements, review the implementation and check what the results support."],
 2:["There are eleven project stories here, plus my professional experience.","The Gold projects show a progression from Excel and Tableau to regression and broader forecasting.","Evidence Lane explores how sources, plans and project results stay connected.","Chapters 4 Change explains campaign strategy; The Book Fairies turns it into a supporter journey.","Hershey and DataCo approach supply-chain questions through public evidence and operational analysis."],
 3:["The opening of each project links to its original website, repository, workbook or report.","Select a skill or tool in the last section to see how it was used in that project.","A forecast, a model and an observed result are different things. The stories keep those limits visible.","Source-linked documents and original reports let you inspect the work behind the explanation.","You can pause my movement with the motion control at the top." ]
};
export default function HomeGuide({active,still,onLand}:{active:number;still:boolean;onLand:()=>void}){
 const [fact,setFact]=useState(0),[position,setPosition]=useState(34),[walking,setWalking]=useState(false),[facing,setFacing]=useState(1),[speaking,setSpeaking]=useState(false),[landingFrame,setLandingFrame]=useState(-1),[breaking,setBreaking]=useState(false),[selectedProp,setSelectedProp]=useState<string|null>(null),[ground,setGround]=useState(0);
 const person=useRef<HTMLDivElement>(null),currentPosition=useRef(34),speech=useRef<SpeechSynthesisUtterance|null>(null);
 const facts=thoughts[active]||thoughts[1];
 const explanations:Record<string,string>={Excel:'Excel appears in the property reporting, Gold model and financial-analysis work. Open those stories to inspect the workbook logic.',Tableau:'Tableau connects prepared records to analytical views in GIAS, Gold and DataCo.',Python:'Python supports source processing, analytical modeling and workflow services across the technical projects.',MCP:'MCP exposes typed operations in Evidence Lane. Each operation keeps its inputs, scope and result explicit.',GitHub:'The opening of each coded project links to its original GitHub repository.',Ingredients:'Hershey separates ingredient evidence, supplier context and benchmark costs instead of treating them as private operational facts.',Logistics:'DataCo studies fulfillment records; Hershey explains a modeled supply-chain flow. Their evidence and limits differ.',Forecasting:'The Gold family progresses from a spreadsheet model to a regression application and broader model comparisons.',Forecast:'A saved forecast is an output to inspect, not proof of future predictive value.',Literacy:'Chapters 4 Change develops the literacy-campaign strategy; The Book Fairies explores the supporter experience.',Campaigns:'Audience framing, positioning, channel roles and planned campaign activities connect the campaign projects.',Experience:'My GIAS work links stakeholder needs, structured property records and recurring reporting.',Projects:'Choose one of the six entrance worlds to find the project stories. Each retains its own contribution and evidence.',Reports:'Original reports and presentations are linked in the relevant project opening.',Workbooks:'Open the original workbook from its project to inspect formulas, inputs and comparisons.','Original files':'Drive, workbook and report links lead to the source deliverables for non-coded work.',Validation:'A check supports the specific calculation or behavior it tested. Its limits stay visible.','Code review':'My role includes directing requirements and reviewing AI-assisted implementation. The repositories make the resulting work inspectable.'};
 const text=selectedProp?(explanations[selectedProp]||facts[fact%facts.length]):facts[fact%facts.length];
 useEffect(()=>{
  setFact(0);setSelectedProp(null);setGround(0);setWalking(false);setLandingFrame(-1);setBreaking(false);
  if(!active||still)return;
  const timers:ReturnType<typeof setTimeout>[]=[];let movement:Animation|undefined;
  const later=(callback:()=>void,ms:number)=>{timers.push(setTimeout(callback,ms));};
  // Freeze the last visible walking location, not the next target or a central spawn.
  setPosition(currentPosition.current);setBreaking(true);setLandingFrame(2);
  later(()=>{setBreaking(false);setLandingFrame(0);movement=person.current?.animate([{translate:'0 -65vh'},{translate:'0 -60vh',offset:.2},{translate:'0 -42vh',offset:.5},{translate:'0 -18vh',offset:.8},{translate:'0 0'}],{duration:650,easing:'linear'});},180);
  later(()=>{setLandingFrame(1);onLand();},830);
  later(()=>setLandingFrame(2),910);later(()=>setLandingFrame(3),1080);later(()=>setLandingFrame(4),1270);later(()=>setLandingFrame(5),1430);later(()=>setLandingFrame(-1),1570);
  let turn=0;const destinations=[64,30,73,45,22,58];
  const move=()=>{const next=destinations[(turn++ +active)%destinations.length];setFacing(next>=currentPosition.current?1:-1);setPosition(next);setGround(active===1?(next>55?12:0):active===2?(next>55?22:5):(next>55?15:0));setSelectedProp(null);setWalking(true);later(()=>{currentPosition.current=next;setWalking(false);},2800);};
  const walkingTimer=setInterval(move,8500),thoughtTimer=setInterval(()=>{setSelectedProp(null);setFact(f=>(f+1)%facts.length);},6800);
  return()=>{const el=person.current,parent=el?.parentElement;if(el&&parent){const a=el.getBoundingClientRect(),b=parent.getBoundingClientRect();currentPosition.current=Math.max(20,Math.min(78,(a.left+a.width/2-b.left)/b.width*100));}movement?.cancel();timers.forEach(clearTimeout);clearInterval(walkingTimer);clearInterval(thoughtTimer);};
 },[active,still,facts.length]);
 useEffect(()=>()=>{if(speech.current&&'speechSynthesis'in window)window.speechSynthesis.cancel();speech.current=null;setSpeaking(false);},[active]);
 const read=()=>{if(!('speechSynthesis'in window))return;if(speaking){window.speechSynthesis.cancel();setSpeaking(false);return;}const message=new SpeechSynthesisUtterance(text);message.rate=.96;message.onend=()=>setSpeaking(false);message.onerror=()=>setSpeaking(false);speech.current=message;setSpeaking(true);window.speechSynthesis.speak(message);};
 return <aside className={`home-guide ground-scene-${active} ${still?'guide-still':''} ${walking?'guide-walking':'guide-resting'} ${landingFrame>=0?'guide-landing':''} ${breaking?'guide-breaking':''}`} style={{'--wander':`${position}%`,'--ground-level':`${ground}px`,'--facing':facing,'--landing-frame':`${Math.max(0,landingFrame)*20}%`} as CSSProperties} aria-label="Praveen's moving Home guide" aria-hidden={!active} inert={!active}>
  <div className="guide-ground" aria-hidden="true"/><div className="guide-rift" aria-hidden="true"/><GuideProps section={active} fact={fact} selected={selectedProp} onSelect={setSelectedProp}/>
  <div ref={person} className="guide-person" aria-hidden="true"><span className={`guide-actor ${landingFrame>=0?'actor-landing':walking?'actor-walking':'actor-presenting'}`}/><span className="guide-shadow"/></div>
  <span className="guide-head-trail" aria-hidden="true"/><div key={`thought-${active}-${fact}-${selectedProp}`} className="guide-thought" aria-live="off"><p key={`${active}-${fact}`}>{text}</p><div className="thought-controls"><span className="thought-progress" aria-hidden="true"/>{'speechSynthesis'in window?<button onClick={read} aria-label={speaking?'Stop reading thought':'Read this thought aloud'}>{speaking?'Stop':'Listen'}</button>:null}</div></div>
 </aside>;
}
